### PR TITLE
Add support for `AS OF SYSTEM TIME`

### PR DESCRIPTION
**Pull request by jakelee8**

### CODE REVIEW

**Comment by tommilligan** [comment]
Hey, thanks for adding to the crate! I see you marked this as draft so won't go to in depth for now, but I like the look of what you've added so far.

Let me know if I can help with anything at all. I've just updated the CI into Github Actions, so that should bug you for the easy stuff.

**Comment by jakelee8** [comment]
Seems like we would need to make a change to Diesel to add this feature. Closing for now.

**Comment by tommilligan** [comment]
For my own interest, what blocked you? Are there any open diesel issues/PRs to keep an eye on?

**Comment by jakelee8** [comment]
I ran into issues doing a "proper" implementation, to add `AS OF SYSTEM TIME` to the `FROM` clause. It looks like we would need to update the upstream `SelectStatement` to support the `AS OF SYSTEM TIME` after or as part of the `FROM` clause: https://github.com/diesel-rs/diesel/blob/master/diesel/src/query_builder/select_statement/mod.rs#L82

Looks like Diesel 2.0 is going to be released soon, so might revisit with the new version.

**Pull request closed without merging**
